### ISSUE TITLE
Is it possible to incude exact match like with fzf ?

### ISSUE THREAD

**Issue by ghost** [nvim-telescope/telescope-fzy-native.nvim#6]
I usually know the exact string im looking for and would prefer if i dont get search results from fuzzy matching.

**Comment by Conni2461** [comment]
Its not part of the `fzy` algorithm. Thats why i ported `fzf` algorithm with the whole `fzf` syntax to a c library so we can use it in telescope. Take a look at https://github.com/nvim-telescope/telescope-fzf-native.nvim

**Comment by ghost** [comment]
I looked at the sample config for fzf native but there doesn't seem to be customization for exact match. Am I missing something ?

**Comment by Conni2461** [comment]
Oh sorry i misunderstood you. You were looking for an option to always enable it?
For `fzf-native` you can type `'` to enable fuzzy matching for the next term but i just added it as an option as well. 

```lua
require('telescope').setup {
  extensions = {
    fzf = {
      fuzzy = false
    }
  }
}
```

**Comment by ghost** [comment]
Yes this is what I was looking for since I don't need fuzzy results.  Thanks.
