### ISSUE TITLE
attempt to call a nil value

### ISSUE THREAD

**Issue by ruanyouxing** [nvim-telescope/telescope-fzy-native.nvim#8]
I run :Telescope fzy_native and it shows this
![image](https://user-images.githubusercontent.com/87190231/150054447-b9c4f21b-8ad7-4350-8e58-0aea154df637.png)
 how to fix this?

**Comment by Conni2461** [comment]
fzy_native does not provide a command to run. Its a sorter function that can be used in the telescope "backend".

Please read the README on how to set it up
